### ISSUE TITLE
Error: Relative import path "http/server.ts" not prefixed with / or ./ or ../ and not in import map

### ISSUE THREAD

**Issue by christ-offer** [zaiste/wren#1]
I had to replace the import with the deno.land url to get it to work. (for the serve input at the top of mod.ts)

Dno if I'm just doing something wrong or not. :)

**Comment by zaiste** [comment]
@christ-offer could you share your project on GitHub? Do you have `deno.json` and `import_map.json` among your project files as shown in the `examples/` folder?

**Comment by zaiste** [comment]
@christ-offer I've just added the *Getting Started* section. Could you try it out and tell me if it works for you?

**Comment by christ-offer** [comment]
Hey! After following the Getting Started section it all worked fine! So we can safely assume PEBKAC on my end here! :)

As someone relatively new to back end in general, and not just new to Deno, I really like the route handling in here!

I havent uploaded the code to Git yet as I'm just playing around with making a middleware for a matrix bot :)

**Comment by zaiste** [comment]
Thanks for the kind words. Let me know if you had other questions, I'd be happy to help. Regarding bots, I'm working on adding an OAuth layer. Maybe something that could be useful for your scenerio here?
